version: "3.9"
services:
  smee:
    restart: always
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: smee/Dockerfile

  rq-worker:
    build:
      context: .
      dockerfile: workers/Dockerfile
    env_file:
      - ./.env
    deploy:
      replicas: 1

  rq-server:
    env_file:
      - ./.env
    image: redis:alpine
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  spackbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    # For development so restart updates server
    volumes:

      # Required for spackbot to have permission to push
      # comment this out if you can't generate
      - ./id_spackbot:/root/.ssh/id_rsa
      - ./id_spackbot.pub:/root/.ssh/id_rsa.pub

      # includes private key
      - ./spackbot:/app/spackbot
    env_file:
      - ./.env
    links:
      - smee

volumes:
  redis-data:
  redis-conf:
